### ISSUE TITLE
1.8.* not working for TS

### ISSUE THREAD

**Issue by nervetattoo** [lbrlabs/pulumi-scaleway#233]
Neither 1.8.0 or 1.8.1 is usable for me with typescript.
## 1.8.1

Not tagged on github, but has a release on npm, leading to this error on *pulumi up|preview*

`error: Could not automatically download and install resource plugin 'pulumi-resource-scaleway' at version v1.8.1, install the plugin using pulumi plugin install resource scaleway v1.8.1 --server github://api.github.com/lbrlabs: error downloading provider scaleway to file: failed to download plugin: scaleway-1.8.1: 404 HTTP error fetching plugin from https://api.github.com/repos/lbrlabs/pulumi-scaleway/releases/tags/v1.8.1. If this is a private GitHub repository, try providing a token via the GITHUB_TOKEN environment variable. See: https://github.com/settings/tokens`
## 1.8.0

Crashes with:

<details>
<summary>Click to show full stack trace for error:
    error: preview failed
    panic: HasAttribute on non-object Type
</summary>

```
    error: preview failed

    panic: HasAttribute on non-object Type
    goroutine 41 [running]:
    github.com/hashicorp/go-cty/cty.Type.HasAttribute({{0x0?, 0x0?}}, {0x10177cdde?, 0x12a7a7aa8?})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/object_type.go:104 +0x94
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.getLocality(0x140009e4e08?, 0x100961084?)
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.16.2/scaleway/helpers.go:913 +0x3c
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.customizeDiffLocalityCheck.func1({0x101f36878?, 0x1400019e010?}, 0x10178aec8?, {0x101c90f00?, 0x14000b7f0c0?})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.16.2/scaleway/helpers.go:930 +0x58
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x14000964bd0, {0x101f36878, 0x1400019e010}, 0x0, 0x14000c0ab10, 0x1400062ce80, {0x101c90f00, 0x14000b7f0c0}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/schema.go:699 +0x3bc
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x101f36878?, 0x1400019e010?}, 0x0, 0x0?, {0x101c90f00?, 0x14000b7f0c0?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220824175045-450992f2f5b9/helper/schema/resource.go:895 +0x50
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x101d3a3c0?, {0x140009228d0?, 0x1017885b2?, 0xb?}}, 0x0?, 0xffffffffffffffff?, 0x140009e5488?, 0x101279b90?, {{{0x101f376e8?, 0x14000112488?}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider_diff.go:73 +0x570
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x1400008c1e0?, {0x0?, 0x0?, 0x140009cf688?}}, {0x1017885b2, 0xb}, {0x0?, 0x0}, {0x101f2e160, 0x14000c0ab10})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfshim/sdk-v2/provider_diff.go:54 +0x1f4
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000026000, {0x101f368e8?, 0x14000c0a9c0?}, 0x140009b11d0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.43.0/pkg/tfbridge/provider.go:873 +0x2d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x101f368e8, 0x14000c0a9c0}, {0x101e60e20?, 0x140009b11d0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.62.0/proto/go/provider_grpc.pb.go:573 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x101f368e8, 0x14000c0a6c0}, {0x101e60e20, 0x140009b11d0}, 0x140009bb540, 0x1400000db90)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x101eed020?, 0x14000026000}, {0x101f368e8, 0x14000c0a6c0}, 0x140009c6b60, 0x1400062cea0)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.62.0/proto/go/provider_grpc.pb.go:575 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x140008ae1e0, {0x101f3db60, 0x14000703ba0}, 0x140009f9440, 0x14000994ff0, 0x102aa3160, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1336 +0xb7c
    google.golang.org/grpc.(*Server).handleStream(0x140008ae1e0, {0x101f3db60, 0x14000703ba0}, 0x140009f9440, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:1704 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:965 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.53.0/server.go:963 +0x290
```
</details>

**Comment by puppetninja** [comment]
can this be fixed please ?

**Comment by dirien** [comment]
Hey @puppetninja and @nervetattoo: Please use `1.9.0` of this provider! 

Sorry for the inconvenience this may caused!
