### ISSUE TITLE
Cannot create an InstanceVolume

### ISSUE THREAD

**Issue by nikaro** [lbrlabs/pulumi-scaleway#250]
Hello,

I'm unable to create an instance volume. I reproduced it with this code:
```python
"""A Python Pulumi program"""

import pulumi
import lbrlabs_pulumi_scaleway as scaleway

scaleway.InstanceVolume(
    "hello-world",
    type="b_ssd",
)
```

Here is the error message when i run `pulumi preview`:
```
    panic: HasAttribute on non-object Type
    goroutine 41 [running]:
    github.com/hashicorp/go-cty/cty.Type.HasAttribute({{0x0?, 0x0?}}, {0x10316e65c?, 0x12bfc6be8?})
    	/home/runner/go/pkg/mod/github.com/hashicorp/go-cty@v1.4.1-0.20200414143053-d3edf31b6320/cty/object_type.go:104 +0x94
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.getLocality(0x14000a28e98?, 0x1022ad084?)
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.22.0/scaleway/helpers.go:915 +0x3c
    github.com/scaleway/terraform-provider-scaleway/v2/scaleway.customizeDiffLocalityCheck.func1({0x10398f3b8?, 0x1400011e018?}, 0x10317cd36?, {0x1036b89e0?, 0x14000a37870?})
    	/home/runner/go/pkg/mod/github.com/scaleway/terraform-provider-scaleway/v2@v2.22.0/scaleway/helpers.go:932 +0x58
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.schemaMap.Diff(0x1400054fc20, {0x10398f3b8, 0x1400011e018}, 0x14000266a90, 0x14000256cc0, 0x14000754d60, {0x1036b89e0, 0x14000a37870}, 0x0)
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/schema.go:699 +0x3bc
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).SimpleDiff(0x0?, {0x10398f3b8?, 0x1400011e018?}, 0x14000266a90, 0x5000?, {0x1036b89e0?, 0x14000a37870?})
    	/home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20230327102345-3fa930f86570/helper/schema/resource.go:895 +0x50
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.simpleDiff({0x10376cba0?, {0x1400054ea20?, 0x103191510?, 0x18?}}, 0x0?, 0xffffffffffffffff?, 0x140002669c0, 0x102be2280?, {{{0x103990298?, 0x1400042c098?}}, ...}, ...)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfshim/sdk-v2/provider_diff.go:87 +0x6ec
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Diff({0x140006b21e0?, {0x0?, 0x0?, 0x140005d5688?}}, {0x103191510, 0x18}, {0x0?, 0x0}, {0x103986680, 0x14000256cc0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfshim/sdk-v2/provider_diff.go:63 +0x210
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Create(0x14000147600, {0x10398f428?, 0x14000256b70?}, 0x1400025a140)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.53.0/pkg/tfbridge/provider.go:721 +0x330
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler.func1({0x10398f428, 0x14000256b70}, {0x1038a78a0?, 0x1400025a140})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.74.0/proto/go/provider_grpc.pb.go:573 +0x74
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x10398f428, 0x14000256870}, {0x1038a78a0, 0x1400025a140}, 0x1400069c2a0, 0x1400053a258)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x30c
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Create_Handler({0x10393a180?, 0x14000147600}, {0x10398f428, 0x14000256870}, 0x140002b4230, 0x1400069c080)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.74.0/proto/go/provider_grpc.pb.go:575 +0x138
    google.golang.org/grpc.(*Server).processUnaryRPC(0x14000264000, {0x103996a80, 0x140005b81a0}, 0x1400027c000, 0x14000256420, 0x1045e4ea0, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xc64
    google.golang.org/grpc.(*Server).handleStream(0x14000264000, {0x103996a80, 0x140005b81a0}, 0x1400027c000, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0x82c
    google.golang.org/grpc.(*Server).serveStreams.func1.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x84
    created by google.golang.org/grpc.(*Server).serveStreams.func1
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x16c
```

**Comment by nikaro** [comment]
Closing as this is a duplicate of #252 and #251. Workaround: downgrade to version `1.7.0`.
